### ISSUE TITLE
Specify the number of servers by number, not by weights

### ISSUE THREAD

**Issue by zoetrope** [cybozu-go/cke#659]
## What

Currently, the number of servers to be join in the cluster is specified by weights.

https://github.com/cybozu-go/cke/blob/c798e29376bfbb00a3fb98261f4359346e35f972/docs/sabakan-integration.md?plain=1#L51

But it is difficult to control.
We want to specify the number of servers by number, not by weight.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions
