### ISSUE TITLE
K8s 1.29: Submit certification request for CKE

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/cke#739]
## What

Submit certification request for CKE 1.29 to CNCF.

## How

https://github.com/cncf/k8s-conformance/blob/master/instructions.md

Update our forked repository https://github.com/cybozu-go/k8s-conformance and create a pull request to `cncf/k8s-conformance`.

All necessary artifacts are (will be) uploaded at https://github.com/cybozu-go/cke/releases/tag/v1.29.0.

## Checklist

- [x] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

```[tasklist]
### Tasks
- [ ] https://github.com/cncf/k8s-conformance/pull/3322
```

**Comment by umezawatakeshi** [comment]
certified.
