### ISSUE TITLE
K8s 1.31: Update for Kubernetes 1.31

### ISSUE THREAD

**Issue by chez-shanpu** [cybozu-go/cke#786]
## What

Upgrade Kubernetes version from 1.30 to 1.31.

ref https://github.com/cybozu-go/cke/issues/761

## How
- Upgrade container image versions
    - CoreDNS, Kubernetes, cke-tools including CNI plugins, etcd, pause, unbound
- Update containerd used in mtest
- Update sonobuoy
- Enable alpha Feature Gates if necessary

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/cke/pull/793
- [ ] https://github.com/cybozu-go/cke/pull/791
- [ ] https://github.com/cybozu-go/cke/pull/794
- [ ] https://github.com/cybozu-go/cke/pull/795
```
